"""
Warning: the csv is generated by CSV because it seems the logic for being standard
changes frequently and doesn't even always follow the same logic. For now this is fine,
but it is probably not 100% right.
"""
import csv

import psycopg2

conn = psycopg2.connect(database="postgres",
                        host="localhost",
                        user="postgres",
                        password="db_pass",
                        port="5432")

cursor = conn.cursor()

with open("mtg_standard_set_rotations.csv", "r") as set_file:
    mtg_set_csv = csv.reader(set_file)
    next(mtg_set_csv)

    max_release_date = '1900-01-01'
    min_release_date = '3000-01-01'
    for row in mtg_set_csv:
        if row[1] > max_release_date:
            max_release_date = row[1]
        if row[1] < min_release_date:
            min_release_date = row[1]
        # seems chatgpt and the other dataset are not 100% matching release date (probably chatgpts fault)
        cursor.execute(
            """
            SELECT id FROM sets
            WHERE LOWER(name)=LOWER(%s)
            AND releasedate::timestamp between (%s::timestamp - INTERVAL '1 month') AND (%s::timestamp + INTERVAL '1 month')
            """,
            [row[0],row[1],row[1]]
        )
        found_record = cursor.fetchone()
        if found_record:
            print(found_record[0])
        else:
            print(found_record)
    print(max_release_date)
    print(min_release_date)

conn.close()
